import { Menu } from "@/types/menu/menu";

export const mockMenuData: { data: Menu[] } = {
  data: [
    {
      id: "1",
      name: "Nasi Goreng Spesial",
      description: "Nasi goreng spesial dengan telur dan ayam.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "1", name: "Makanan" },
    },
    {
      id: "2",
      name: "Ayam Bakar Madu",
      description: "Ayam bakar dengan bumbu madu.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "1", name: "Makanan" },
    },
    {
      id: "3",
      name: "Mie Goreng Jawa",
      description: "Mie goreng khas Jawa.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "1", name: "Makanan" },
    },
    {
      id: "4",
      name: "Sate Ayam",
      description: "Sate ayam dengan bumbu kacang.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "1", name: "Makanan" },
    },
    {
      id: "5",
      name: "Es Teh Manis",
      description: "Minuman es teh manis.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "2", name: "Minuman" },
    },
    {
      id: "6",
      name: "Bakso Urat",
      description: "Bakso urat dengan kuah kaldu.",
      image_url: "/images/BackgroundHero.png",
      is_available: true,
      price: "20000",
      category: { id: "1", name: "Makanan" },
    },
  ],
};
